### ISSUE TITLE
How to add?

### ISSUE THREAD

**Issue by nutsofamily** [TheChrisTech/Hubitat-SharkIQRobot#3]
Hello I would like to replace my SharkIQ integ with this one as the Sharkiq reports indefinitely returning to dock.
I tried adding the git to repositories but does not show up?

**Comment by TheChrisTech** [comment]
Here's a link on how to install the custom driver: https://docs.hubitat.com/index.php?title=How_to_Install_Custom_Drivers
and the RAW link to use to import: https://raw.githubusercontent.com/TheChrisTech/Hubitat-SharkIQRobot/1.0.8/SharkIQRobotDriver.groovy
